/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CommandConsole: typeof import('./src/components/CommandConsole.vue')['default']
    CommitButton: typeof import('./src/components/buttons/CommitButton.vue')['default']
    CommonDialog: typeof import('./src/components/CommonDialog.vue')['default']
    DirectorySelector: typeof import('./src/components/DirectorySelector.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSplitterPanel: typeof import('element-plus/es')['ElSplitterPanel']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FileActionButtons: typeof import('./src/components/FileActionButtons.vue')['default']
    FileDiffViewer: typeof import('./src/components/FileDiffViewer.vue')['default']
    FileGroup: typeof import('./src/components/FileGroup.vue')['default']
    GitActionButtons: typeof import('./src/components/GitActionButtons.vue')['default']
    GitCommandPreview: typeof import('./src/components/GitCommandPreview.vue')['default']
    GitGlobalSettingsDialog: typeof import('./src/components/GitGlobalSettingsDialog.vue')['default']
    GlobalLoading: typeof import('./src/components/GlobalLoading.vue')['default']
    I18nTest: typeof import('./src/components/I18nTest.vue')['default']
    InlineCard: typeof import('./src/components/InlineCard.vue')['default']
    LanguageSwitcher: typeof import('./src/components/LanguageSwitcher.vue')['default']
    OptionSwitchCard: typeof import('./src/components/OptionSwitchCard.vue')['default']
    PushButton: typeof import('./src/components/buttons/PushButton.vue')['default']
    QuickPushButton: typeof import('./src/components/buttons/QuickPushButton.vue')['default']
    StageButton: typeof import('./src/components/buttons/StageButton.vue')['default']
    SuccessModal: typeof import('./src/components/SuccessModal.vue')['default']
    TemplateManager: typeof import('./src/components/TemplateManager.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
